import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Stitch Pan-African Professionalism design tokens
        'surface-container-high': '#dbeaf6',
        'on-tertiary-fixed-variant': '#005139',
        'outline-variant': '#bdcbb3',
        'on-primary-fixed-variant': '#065300',
        'error-container': '#ffdad6',
        'surface-container-lowest': '#ffffff',
        'on-primary': '#ffffff',
        'primary-container': '#14a800',
        'on-surface': '#0e1d26',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        background: '#f5faff',
        'on-tertiary-container': '#003121',
        'surface-dim': '#ccdce8',
        'tertiary-container': '#00a577',
        'surface-container-highest': '#d5e5f0',
        secondary: '#5d5d6f',
        'tertiary-fixed-dim': '#30e0a6',
        'on-primary-container': '#023200',
        'on-secondary': '#ffffff',
        'primary-fixed': '#79ff5f',
        outline: '#6e7b67',
        'surface-variant': '#d5e5f0',
        'inverse-on-surface': '#e3f3ff',
        'secondary-container': '#e3e0f7',
        'surface-container-low': '#e9f5ff',
        'on-surface-variant': '#3e4a38',
        'secondary-fixed': '#e3e0f7',
        'inverse-primary': '#5ce145',
        'on-tertiary': '#ffffff',
        'surface-container': '#e0f0fc',
        'primary-fixed-dim': '#5ce145',
        'on-secondary-container': '#636375',
        'secondary-fixed-dim': '#c6c4da',
        primary: '#0a6e00',
        'tertiary-fixed': '#59fdc0',
        'surface-bright': '#f5faff',
        'on-primary-fixed': '#012200',
        tertiary: '#006c4d',
        surface: '#f5faff',
        'surface-tint': '#0a6e00',
        'on-tertiary-fixed': '#002115',
        'on-secondary-fixed': '#1a1a2a',
        error: '#ba1a1a',
        'on-secondary-fixed-variant': '#464557',
        'inverse-surface': '#24323b',
        'on-background': '#0e1d26',

        // Legacy brand tokens kept for backwards compat on landing page
        brand: {
          primary: '#0a6e00',
          'primary-container': '#14a800',
          secondary: '#5d5d6f',
          'secondary-container': '#e3e0f7',
          tertiary: '#006c4d',
          'tertiary-container': '#00a577',
          navy: '#1e1e2e',
          surface: '#f5faff',
          'on-surface': '#0e1d26',
          'on-surface-variant': '#3e4a38',
          outline: '#6e7b67',
          'outline-variant': '#bdcbb3',
        },
      },
      spacing: {
        margin: '32px',
        gutter: '24px',
        unit: '8px',
        'container-max': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        sans: ['Manrope', 'system-ui', 'sans-serif'],
        mono: ['IBM Plex Mono', 'monospace'],
        display: ['Space Grotesk', 'system-ui', 'sans-serif'],
        body: ['Manrope', 'system-ui', 'sans-serif'],
        'body-sm': ['Manrope', 'system-ui', 'sans-serif'],
        'label-mono': ['IBM Plex Mono', 'monospace'],
        h1: ['Space Grotesk', 'system-ui', 'sans-serif'],
        h2: ['Space Grotesk', 'system-ui', 'sans-serif'],
        h3: ['Space Grotesk', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-mono': ['13px', { lineHeight: '1.0', letterSpacing: '0.02em', fontWeight: '500' }],
        body: ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        h2: ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        h1: ['56px', { lineHeight: '1.1', fontWeight: '700' }],
        h3: ['28px', { lineHeight: '1.3', fontWeight: '600' }],
      },
      backgroundImage: {
        'hero-gradient': 'linear-gradient(135deg, #f5faff 0%, #e0f0fc 100%)',
        'card-gradient': 'linear-gradient(135deg, #ffffff 0%, #f5faff 100%)',
        'brand-gradient': 'linear-gradient(135deg, #0a6e00 0%, #14a800 100%)',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.5s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
